### ISSUE TITLE
could you help to investigate the performance problem https://github.com/panjf2000/gnet/issues/296

### ISSUE THREAD

**Issue by slow-zhang** [IceFireDB/redhub#6]
https://github.com/panjf2000/gnet/issues/296

**Comment by Jchicode** [comment]
I read your issue, but I don’t understand what you mean, can you show me your code?

**Comment by Jchicode** [comment]
Maybe you can try redis pipeline

**Comment by slow-zhang** [comment]
> I read your issue, but I don’t understand what you mean, can you show me your code?

I compare `redhub` with a simple go-net redis, here is my code: https://github.com/slow-zhang/gnet-test/blob/main/main.go#L98. (http listen in dir2)
and I find the go-net implementation is faster

> Maybe you can try redis pipeline

I will not use redis-pipeline for I will not use this feature in my app
