### ISSUE TITLE
no idea why but if you terminate the example server, 

### ISSUE THREAD

**Issue by superdolt** [IceFireDB/redhub#8]
no idea why but if you terminate the example server, even when the process is killed, the address is still "already in use" for a while before it is available. why is this so? the port is not available even when the process is killed.

2021/12/10 07:17:30 started redhub server at :1234
2021/12/10 07:17:30 bind: address already in use

**Comment by Jchicode** [comment]
Thank you, I seem to have reproduced this problem, and I will consider fixing it in the future

**Comment by superdolt** [comment]
mind sharing why this is so?

**Comment by Jchicode** [comment]
> mind sharing why this is so?

I think this is the reason：When the port is released, it goes into the TIME_WAIT state to prevent duplicate packets that were delayed en route to the first connection to be delivered to the second connection.
