### ISSUE TITLE
possible to fix this?

### ISSUE THREAD

**Issue by hiqsociety** [IceFireDB/redhub#9]
https://github.com/IceFireDB/redhub/issues/8

it shld be an opened issue

**Comment by superdolt** [comment]
any quick fix to this issue for the moment? as "address already in use" this way is slowing down testing. need to wait. how to quickly ensure the port is ready for reuse?

**Comment by Jchicode** [comment]
Hi, in the latest commit, added whether SO_REUSEPORT socket option is set.
You can set reusePort=true at startup.

**Comment by superdolt** [comment]
ok thx
